# Generated by Django 5.1.5 on 2026-01-17 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Public", "Public"),
                            ("Recruteur", "Recruteur"),
                            ("Prive", "Privé"),
                        ],
                        default="Public",
                        help_text="Niveau de visibilité du contenu",
                        max_length=20,
                        verbose_name="Visibilité",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Ex: Développeur Full-Stack",
                        max_length=200,
                        verbose_name="Poste occupé",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        help_text="Nom de l'entreprise ou organisation",
                        max_length=200,
                        verbose_name="Entreprise/Organisation",
                    ),
                ),
                (
                    "company_url",
                    models.URLField(
                        blank=True,
                        help_text="URL du site web de l'entreprise",
                        verbose_name="Site web de l'entreprise",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Ville, Pays",
                        max_length=200,
                        verbose_name="Localisation",
                    ),
                ),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("Stage", "Stage"),
                            ("Emploi", "Emploi"),
                            ("Freelance", "Freelance"),
                            ("Alternance", "Alternance"),
                            ("Benevolat", "Bénévolat"),
                        ],
                        help_text="Stage, Emploi, Freelance, etc.",
                        max_length=20,
                        verbose_name="Type d'expérience",
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        help_text="Format: YYYY-MM (ex: 2021-03)",
                        max_length=7,
                        verbose_name="Date de début",
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True,
                        help_text="Format: YYYY-MM. Laisser vide si en cours",
                        max_length=7,
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher si vous occupez toujours ce poste",
                        verbose_name="Poste actuel",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Présentation générale du poste et contexte",
                        verbose_name="Description du poste",
                    ),
                ),
                (
                    "missions",
                    models.TextField(
                        help_text="Liste des missions (une par ligne ou séparées par des puces)",
                        verbose_name="Missions principales",
                    ),
                ),
                (
                    "achievements",
                    models.TextField(
                        blank=True,
                        help_text="Résultats concrets obtenus (chiffrés si possible)",
                        verbose_name="Réalisations/Résultats",
                    ),
                ),
                (
                    "technologies",
                    models.TextField(
                        blank=True,
                        help_text="Liste des technologies, langages, outils (séparés par des virgules)",
                        verbose_name="Technologies utilisées",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage (0 = premier)",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expérience professionnelle",
                "verbose_name_plural": "Expériences professionnelles",
                "db_table": "professional_experience",
                "ordering": ["display_order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Public", "Public"),
                            ("Recruteur", "Recruteur"),
                            ("Prive", "Privé"),
                        ],
                        default="Public",
                        help_text="Niveau de visibilité du contenu",
                        max_length=20,
                        verbose_name="Visibilité",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ex: Bootcamp React Avancé",
                        max_length=255,
                        verbose_name="Titre de la formation",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        help_text="Organisation ou plateforme proposant la formation",
                        max_length=200,
                        verbose_name="Organisme",
                    ),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("En_ligne", "En ligne"),
                            ("Presentiel", "Présentiel"),
                            ("Hybride", "Hybride"),
                        ],
                        default="En_ligne",
                        help_text="En ligne, Présentiel, Hybride",
                        max_length=20,
                        verbose_name="Type de formation",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers la page de la formation",
                        verbose_name="URL de la formation",
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        help_text="Format: YYYY-MM",
                        max_length=7,
                        verbose_name="Date de début",
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True,
                        help_text="Format: YYYY-MM. Laisser vide si en cours",
                        max_length=7,
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "is_ongoing",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher si la formation est toujours en cours",
                        verbose_name="Formation en cours",
                    ),
                ),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Durée totale de la formation en heures",
                        null=True,
                        verbose_name="Durée (heures)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description du contenu de la formation",
                        verbose_name="Description",
                    ),
                ),
                (
                    "skills_acquired",
                    models.TextField(
                        blank=True,
                        help_text="Liste des compétences acquises (une par ligne ou séparées par des virgules)",
                        verbose_name="Compétences acquises",
                    ),
                ),
                (
                    "has_certificate",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher si un certificat a été délivré",
                        verbose_name="Certificat obtenu",
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers le certificat en ligne (si disponible)",
                        verbose_name="URL du certificat",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage (0 = premier)",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation complémentaire",
                "verbose_name_plural": "Formations complémentaires",
                "db_table": "professional_training",
                "ordering": ["display_order", "-start_date"],
            },
        ),
    ]
