# Generated by Django 5.1.5 on 2026-01-18 00:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("education", "0001_initial"),
        ("professional", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Python, React, Leadership, etc.",
                        max_length=100,
                        verbose_name="Nom de la compétence",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Langage", "Langage de programmation"),
                            ("Framework", "Framework"),
                            ("Outil", "Outil"),
                            ("Soft_Skill", "Compétence transversale"),
                            ("Autre", "Autre"),
                        ],
                        default="Langage",
                        help_text="Type de compétence",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Debutant", "Débutant"),
                            ("Intermediaire", "Intermédiaire"),
                            ("Avance", "Avancé"),
                            ("Expert", "Expert"),
                        ],
                        default="Intermediaire",
                        help_text="Auto-évaluation du niveau",
                        max_length=20,
                        verbose_name="Niveau de maîtrise",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description de la compétence et contexte d'utilisation",
                        verbose_name="Description",
                    ),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Nombre d'années d'expérience avec cette compétence",
                        max_digits=4,
                        null=True,
                        verbose_name="Années d'expérience",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher pour les compétences principales à mettre en avant",
                        verbose_name="Compétence principale",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage (0 = premier)",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "related_certifications",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Certifications validant cette compétence",
                        related_name="skills",
                        to="education.certification",
                        verbose_name="Certifications associées",
                    ),
                ),
                (
                    "related_projects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Projets dans lesquels cette compétence a été utilisée",
                        related_name="skills",
                        to="projects.project",
                        verbose_name="Projets associés",
                    ),
                ),
                (
                    "related_trainings",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Formations où cette compétence a été acquise",
                        related_name="skills",
                        to="professional.training",
                        verbose_name="Formations associées",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compétence",
                "verbose_name_plural": "Compétences",
                "db_table": "skills_skill",
                "ordering": ["display_order", "category", "name"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
