# Generated by Django 5.1.5 on 2026-01-17 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Public", "Public"),
                            ("Recruteur", "Recruteur"),
                            ("Prive", "Privé"),
                        ],
                        default="Public",
                        help_text="Niveau de visibilité du contenu",
                        max_length=20,
                        verbose_name="Visibilité",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: AWS Certified Solutions Architect",
                        max_length=255,
                        verbose_name="Nom de la certification",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        help_text="Organisation délivrant la certification",
                        max_length=255,
                        verbose_name="Organisme",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Coursera, Udemy, LinkedIn Learning, etc.",
                        max_length=200,
                        verbose_name="Plateforme",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        help_text="Date à laquelle la certification a été obtenue",
                        verbose_name="Date d'obtention",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True,
                        help_text="Date d'expiration (si applicable)",
                        null=True,
                        verbose_name="Date d'expiration",
                    ),
                ),
                (
                    "does_not_expire",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher si la certification n'expire jamais",
                        verbose_name="Sans expiration",
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant unique de la certification",
                        max_length=200,
                        verbose_name="ID de certification",
                    ),
                ),
                (
                    "credential_url",
                    models.URLField(
                        blank=True,
                        help_text="Lien pour vérifier la certification en ligne",
                        verbose_name="URL de vérification",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description des compétences acquises",
                        verbose_name="Description",
                    ),
                ),
                (
                    "skills_acquired",
                    models.TextField(
                        blank=True,
                        help_text="Liste des compétences obtenues (une par ligne ou séparées par des virgules)",
                        verbose_name="Compétences acquises",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage (0 = premier)",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "db_table": "education_certification",
                "ordering": ["display_order", "-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Diploma",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Public", "Public"),
                            ("Recruteur", "Recruteur"),
                            ("Prive", "Privé"),
                        ],
                        default="Public",
                        help_text="Niveau de visibilité du contenu",
                        max_length=20,
                        verbose_name="Visibilité",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ex: Master en Intelligence Artificielle",
                        max_length=255,
                        verbose_name="Intitulé du diplôme",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        help_text="Nom de l'université ou école",
                        max_length=255,
                        verbose_name="Établissement",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BTS", "BTS"),
                            ("DUT", "DUT"),
                            ("Licence", "Licence"),
                            ("Licence_Pro", "Licence Professionnelle"),
                            ("Master", "Master"),
                            ("Master_Pro", "Master Professionnel"),
                            ("Ingenieur", "Ingénieur"),
                            ("Doctorat", "Doctorat"),
                            ("Autre", "Autre"),
                        ],
                        help_text="Niveau du diplôme",
                        max_length=20,
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        help_text="Ex: Informatique, Data Science, etc.",
                        max_length=200,
                        verbose_name="Domaine d'étude",
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        help_text="Format: YYYY-MM (ex: 2020-09)",
                        max_length=7,
                        verbose_name="Date de début",
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        help_text="Format: YYYY-MM (ex: 2022-06)",
                        max_length=7,
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "honors",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Très Bien, Bien, Assez Bien",
                        max_length=100,
                        verbose_name="Mention",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée du cursus et des compétences acquises",
                        verbose_name="Description",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Note finale ou GPA (optionnel)",
                        max_length=50,
                        verbose_name="Note/GPA",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage (0 = premier)",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diplôme",
                "verbose_name_plural": "Diplômes",
                "db_table": "education_diploma",
                "ordering": ["display_order", "-end_date"],
            },
        ),
    ]
