# Generated by Django 5.1.5 on 2026-01-18 00:38

import apps.core.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proof",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Public", "Public"),
                            ("Recruteur", "Recruteur"),
                            ("Prive", "Privé"),
                        ],
                        default="Public",
                        help_text="Niveau de visibilité du contenu",
                        max_length=20,
                        verbose_name="Visibilité",
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        help_text="ID de l'objet auquel cette preuve est attachée",
                        verbose_name="ID de l'objet",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titre descriptif du fichier",
                        max_length=200,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description optionnelle du fichier",
                        verbose_name="Description",
                    ),
                ),
                (
                    "proof_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Vidéo"),
                            ("pdf", "PDF"),
                            ("document", "Document"),
                        ],
                        help_text="Type de fichier (image, vidéo, PDF, document)",
                        max_length=20,
                        verbose_name="Type de preuve",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Fichier de la preuve",
                        upload_to=apps.core.utils.generate_filename,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Taille du fichier en octets",
                        null=True,
                        verbose_name="Taille du fichier",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom du fichier tel qu'uploadé",
                        max_length=255,
                        verbose_name="Nom du fichier original",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="Type MIME du fichier",
                        max_length=100,
                        verbose_name="Type MIME",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage (0 = premier)",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type d'objet auquel cette preuve est attachée",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Type de contenu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preuve",
                "verbose_name_plural": "Preuves",
                "db_table": "proofs_proof",
                "ordering": ["display_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="proofs_proo_content_43582f_idx",
                    )
                ],
            },
        ),
    ]
