# Generated by Django 5.1.5 on 2026-01-17 04:15

import apps.core.utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo professionnelle (format recommandé: 400x400px)",
                        null=True,
                        upload_to=apps.core.utils.generate_filename,
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "professional_title",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Développeur Full-Stack, Data Scientist, etc.",
                        max_length=200,
                        verbose_name="Titre professionnel",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Courte présentation professionnelle",
                        verbose_name="Biographie",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Phrase courte et percutante",
                        max_length=150,
                        verbose_name="Phrase d'accroche",
                    ),
                ),
                (
                    "professional_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email de contact professionnel (peut être différent du compte)",
                        max_length=254,
                        verbose_name="Email professionnel",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de téléphone professionnel",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Ville, Pays",
                        max_length=200,
                        verbose_name="Localisation",
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de votre site web ou portfolio",
                        verbose_name="Site web personnel",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de votre profil GitHub",
                        verbose_name="GitHub",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de votre profil LinkedIn",
                        verbose_name="LinkedIn",
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de votre profil Twitter",
                        verbose_name="Twitter/X",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("disponible_stage", "Disponible pour un stage"),
                            ("disponible_emploi", "Disponible pour un emploi"),
                            ("disponible_freelance", "Disponible en freelance"),
                            ("disponible_projet", "Disponible pour des projets"),
                            ("non_disponible", "Non disponible actuellement"),
                        ],
                        default="non_disponible",
                        help_text="Statut de disponibilité actuel",
                        max_length=30,
                        verbose_name="Disponibilité",
                    ),
                ),
                (
                    "availability_date",
                    models.DateField(
                        blank=True,
                        help_text="Date à partir de laquelle vous êtes disponible",
                        null=True,
                        verbose_name="Date de disponibilité",
                    ),
                ),
                (
                    "show_email",
                    models.BooleanField(
                        default=True,
                        help_text="Afficher l'email professionnel sur le portfolio public",
                        verbose_name="Afficher l'email",
                    ),
                ),
                (
                    "show_phone",
                    models.BooleanField(
                        default=False,
                        help_text="Afficher le téléphone sur le portfolio public",
                        verbose_name="Afficher le téléphone",
                    ),
                ),
                (
                    "show_location",
                    models.BooleanField(
                        default=True,
                        help_text="Afficher la localisation sur le portfolio public",
                        verbose_name="Afficher la localisation",
                    ),
                ),
                (
                    "is_profile_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Indique si le profil est suffisamment rempli",
                        verbose_name="Profil complet",
                    ),
                ),
                (
                    "profile_views",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre de fois que le profil a été consulté",
                        verbose_name="Nombre de vues",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil",
                "verbose_name_plural": "Profils",
                "db_table": "profiles_profile",
                "ordering": ["-created_at"],
            },
        ),
    ]
