# Generated by Django 5.1.5 on 2026-01-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="portfolio_slug",
            field=models.SlugField(
                blank=True,
                help_text="Utilisé dans l'URL publique (ex: /ton-nom). Laissez vide pour génération automatique.",
                max_length=120,
                null=True,
                unique=True,
                verbose_name="Slug du portfolio",
            ),
        ),
    ]
