# Generated by Django 5.1.5 on 2026-01-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_portfolio_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="empty_about_text",
            field=models.TextField(
                blank=True,
                help_text="Message affiché quand la biographie est vide.",
                null=True,
                verbose_name="Message Section À Propos vide",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="empty_education_text",
            field=models.TextField(
                blank=True,
                help_text="Message affiché quand aucune formation n'est listée.",
                null=True,
                verbose_name="Message Section Éducation vide",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="empty_experience_text",
            field=models.TextField(
                blank=True,
                help_text="Message affiché quand aucune expérience n'est listée.",
                null=True,
                verbose_name="Message Section Expériences vide",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="empty_projects_text",
            field=models.TextField(
                blank=True,
                help_text="Message affiché quand aucun projet n'est listé.",
                null=True,
                verbose_name="Message Section Projets vide",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="empty_skills_text",
            field=models.TextField(
                blank=True,
                help_text="Message affiché quand aucune compétence n'est listée.",
                null=True,
                verbose_name="Message Section Compétences vide",
            ),
        ),
    ]
