# Generated by Django 5.1.5 on 2026-01-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_empty_about_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="trait_1_description",
            field=models.TextField(
                default="Fasciné par les systèmes intelligents et leur capacité à résoudre des problèmes complexes.",
                verbose_name="Description Trait 1",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="trait_1_title",
            field=models.CharField(
                default="Passionné", max_length=50, verbose_name="Titre Trait 1"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="trait_2_description",
            field=models.TextField(
                default="Toujours en quête de nouveaux défis pour repousser les limites de mes compétences.",
                verbose_name="Description Trait 2",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="trait_2_title",
            field=models.CharField(
                default="Déterminé", max_length=50, verbose_name="Titre Trait 2"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="trait_3_description",
            field=models.TextField(
                default="Toujours à l'affût des dernières avancées en IA pour créer des solutions innovantes.",
                verbose_name="Description Trait 3",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="trait_3_title",
            field=models.CharField(
                default="Innovant", max_length=50, verbose_name="Titre Trait 3"
            ),
        ),
    ]
