# Generated by Django 5.1.5 on 2026-02-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_trait_1_description_profile_trait_1_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="public_template",
            field=models.CharField(
                choices=[("tech_alchemist", "Tech Alchemist"), ("minimal", "Minimal")],
                default="tech_alchemist",
                help_text="Template utilisé pour l'affichage du portfolio public",
                max_length=50,
                verbose_name="Template public",
            ),
        ),
    ]
