# Generated by Django 5.1.5 on 2026-01-18 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruiterLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Token sécurisé unique",
                        max_length=64,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom descriptif pour identifier ce lien (ex: Lien pour Google)",
                        max_length=200,
                        verbose_name="Nom du lien",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Note ou contexte de ce lien",
                        verbose_name="Description",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Date et heure d'expiration du lien",
                        verbose_name="Date d'expiration",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Le lien peut être désactivé manuellement",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre de fois que ce lien a été utilisé",
                        verbose_name="Nombre d'accès",
                    ),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date du dernier accès avec ce lien",
                        null=True,
                        verbose_name="Dernier accès",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Propriétaire du portfolio",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien Recruteur",
                "verbose_name_plural": "Liens Recruteurs",
                "db_table": "recruiter_access_link",
                "ordering": ["-created_at"],
            },
        ),
    ]
