# Generated by Django 5.1.5 on 2026-01-17 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("Public", "Public"),
                            ("Recruteur", "Recruteur"),
                            ("Prive", "Privé"),
                        ],
                        default="Public",
                        help_text="Niveau de visibilité du contenu",
                        max_length=20,
                        verbose_name="Visibilité",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Nom du projet",
                        max_length=255,
                        verbose_name="Titre du projet",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Résumé en une phrase (300 caractères max)",
                        max_length=300,
                        verbose_name="Description courte",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description complète du projet, contexte et objectifs",
                        verbose_name="Description détaillée",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("Academique", "Académique"),
                            ("Personnel", "Personnel"),
                            ("Professionnel", "Professionnel"),
                        ],
                        default="Personnel",
                        help_text="Académique, Personnel, Professionnel",
                        max_length=20,
                        verbose_name="Type de projet",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("En_cours", "En cours"),
                            ("Termine", "Terminé"),
                            ("Archive", "Archivé"),
                        ],
                        default="En_cours",
                        help_text="En cours, Terminé, Archivé",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Développeur Full-Stack, Lead Developer, etc.",
                        max_length=200,
                        verbose_name="Rôle occupé",
                    ),
                ),
                (
                    "team_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre de personnes dans l'équipe (laisser vide si projet solo)",
                        null=True,
                        verbose_name="Taille de l'équipe",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Entreprise, université ou organisation (si applicable)",
                        max_length=200,
                        verbose_name="Organisation",
                    ),
                ),
                (
                    "start_date",
                    models.CharField(
                        help_text="Format: YYYY-MM",
                        max_length=7,
                        verbose_name="Date de début",
                    ),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True,
                        help_text="Format: YYYY-MM. Laisser vide si en cours",
                        max_length=7,
                        verbose_name="Date de fin",
                    ),
                ),
                (
                    "technologies",
                    models.TextField(
                        help_text="Liste des technologies, langages, frameworks (séparés par des virgules)",
                        verbose_name="Technologies utilisées",
                    ),
                ),
                (
                    "key_features",
                    models.TextField(
                        help_text="Liste des principales fonctionnalités (une par ligne)",
                        verbose_name="Fonctionnalités clés",
                    ),
                ),
                (
                    "challenges",
                    models.TextField(
                        blank=True,
                        help_text="Difficultés techniques rencontrées et comment elles ont été surmontées",
                        verbose_name="Défis rencontrés",
                    ),
                ),
                (
                    "solutions",
                    models.TextField(
                        blank=True,
                        help_text="Solutions techniques mises en place",
                        verbose_name="Solutions apportées",
                    ),
                ),
                (
                    "achievements",
                    models.TextField(
                        blank=True,
                        help_text="Résultats obtenus, impact du projet (chiffrés si possible)",
                        verbose_name="Réalisations/Résultats",
                    ),
                ),
                (
                    "learning_outcomes",
                    models.TextField(
                        blank=True,
                        help_text="Ce que ce projet vous a permis d'apprendre",
                        verbose_name="Compétences acquises",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers le repository GitHub",
                        verbose_name="GitHub",
                    ),
                ),
                (
                    "demo_url",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers la démo/application en ligne",
                        verbose_name="Démo en ligne",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers une vidéo de démonstration (YouTube, Vimeo, etc.)",
                        verbose_name="Vidéo de présentation",
                    ),
                ),
                (
                    "documentation_url",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers la documentation du projet",
                        verbose_name="Documentation",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image principale du projet (1200x630px recommandé)",
                        null=True,
                        upload_to="projects/covers/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher pour mettre ce projet en avant sur le portfolio",
                        verbose_name="Projet mis en avant",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage (0 = premier)",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "db_table": "projects_project",
                "ordering": ["display_order", "-start_date"],
            },
        ),
    ]
