# Generated by Django 5.1.5 on 2026-01-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="team_size",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text="Nombre de personnes dans l'équipe (laisser vide si projet solo)",
                null=True,
                verbose_name="Taille de l'équipe",
            ),
        ),
    ]
